language: java
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "mvn deploy --settings target/travis/settings.xml"

# whitelist
branches:
  only:
    - develop

env:
  global:
    - secure: "kLm3xarqqvI9W6KvWupcTOau2iPfha+LYteCdZCiq+lwnXyEG/FUx1v71New\nowQQTnfvXuWMR/kH0BnMm8WYJSImUDMkE0v90uoY/J+5FcrzfVBQO4lj16Jh\n7629+BWjfWoK9yCTUCt0i0Qsg9qbyGT/ErADdlu/c87Byd3GPLY="
    - secure: "XlDG6tg4wpGhsiMC7wzlRqOo3Q6T+xYqSMCx+nWwGkF1RTiuOwgS0vXOMFc4\nmONmhUa2s6ydZKlTO6HhWtbV02gKMrCbwcZf0SDnP8UMyTdJY7LgR752fXuj\naqrSzigkAm3Krqu2IT6M0RP/ZjOqK4JH9Kal9gBUlgUC+R2rCd8="